meta_product_name: "Cura"
meta_title: "Cura - Medicine at your door step"
meta_description: "Faites vous livrer vos medicaments o√π vous le souhaitez"
meta_image: "ogimage.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
